### ISSUE TITLE
Can i grt demo source project?

### ISSUE THREAD

**Issue by Prestapro** [itgalaxy/webpack-webfont#6]
Hello,
This is a great plugin!)
I'm just starting to learn webpak, I also do not know English perfectly.
Can I get a sample project?
It's same difficult for me.

Regards,
Alexander.

**Comment by evilebottnawi** [comment]
@Prestapro Thanks for feedback, plugin is in alpha, so some things may not work too well, what you do not understand?

**Comment by Prestapro** [comment]
I'm trying to use the plugin to convert not only SVG icons.
My task is to convert fonts from TTF to WOFF and WOFF2
I have not found a way to do this.

**Comment by evilebottnawi** [comment]
@Prestapro this plugin use https://github.com/itgalaxy/webfont as api, basic support only svg icons, If you have a suggestion how we can make fonts not only from svg create issue in `webfont` repo, not here

**Comment by evilebottnawi** [comment]
Moved to https://github.com/itgalaxy/webfont
