### ISSUE TITLE
Infinite recompilation occurs

### ISSUE THREAD

**Issue by dudewad** [itgalaxy/webpack-webfont#77]
I'm not sure why but when the output SCSS file for the webfont is part of the Webpack watcher list, it causes an infinite compilation loop.

Compiler runs
-> webpack-webfont generates files/SCSS
-> Watcher triggers because of fontFile.scss change
-> webpack-webfont generates files/SCSS
-> Watcher triggers because of... you get the point.

How do I keep this from happening?

**Comment by evilebottnawi** [comment]
@dudewad known issue, just add `fonts` and `css` to `webpack.WatchIgnorePlugin(...optins)`, in near future i rewrite plugin on loader and we avoid this problems and speed up build time, thanks!

**Comment by dudewad** [comment]
Yeah I tried that but now a recompile of the webfont won't kick off a watch-run cycle, which is problematic. Because the font files themselves change and are requested by the browser, but the SCSS isn't recompiled by the sass loader due to a lack of a compilation, you end up with https://github.com/itgalaxy/webpack-webfont/issues/7
Its why I mentioned they were kind of related.

**Comment by evilebottnawi** [comment]
@dudewad PR welcome, if your found solution, sorry, but no time now for this :disappointed:

**Comment by dudewad** [comment]
@evilebottnawi I understand. Just got back from a trip, I'll spend some time today looking at this - but honestly, I'm not even sure that this is a problem with the wepack-webfont plugin, because it's not the one triggering the recompile. I think there is a way to flag the compiler for another pass or something that keeps this from being an issue, though. Sigh.... back to reading webpack  source code :(

**Comment by evilebottnawi** [comment]
@dudewad sorry, don't have time now for this, very busy, PR welcome, in any case, I'll try to find the time to look what is buggy

**Comment by dudewad** [comment]
@evilebottnawi I have a working solution, I'll ship a PR in a bit here. I am a bit webpack illiterate though so I am not exactly certain that this is the best approach. Would love for you to review it when I open it.

**Comment by dudewad** [comment]
@evilebottnawi Any chance you'll get the time in the next day or so to look at this an pull it in? I'm coming up to a point where I'll be stuck if I can't update via npm w/o this fix.

**Comment by dudewad** [comment]
@evilebottnawi Thank you for merging. I'm going to leave this open for a bit and make sure that there aren't any issues that I can discover, then I'll close. You can also close whenever you want!

**Comment by dudewad** [comment]
@evilebottnawi I'm not sure what happened but the new package is different from what I have, and its broken. Did you test it before merging?

**Comment by dudewad** [comment]
Oh I see the problem -- I *think* I failed to commit a conversion of a function literal to a fat-arrow. Scoping issues caused 'this' references to be bad. I'm pushing up a new PR to fix the issue now.

**Comment by dudewad** [comment]
Okay, I am marking this resolved. I've been successfully using it without ignoring any files now for several days.
