### ISSUE TITLE
 svg and webfont aspect ratios differs

### ISSUE THREAD

**Issue by wasa4587** [itgalaxy/webpack-webfont#88]
My svg is 512*512
```
...
   x="0px"
   y="0px"
   width="512"
   height="512"
   viewBox="0 0 512 512"
...
```
The aspect ratio of my svg is 1:1, but when i use the generated webfont icon, the aspect ratio is not 1:1

![image](https://user-images.githubusercontent.com/2035706/32870230-8379be78-ca40-11e7-92ac-a0dd11efc058.png)

The config
```
      new WebfontPlugin({
          files: helpers.root('src/assets/svg/*.svg'),
          css: true,
          maxConcurrency: 1,
          template: 'css',
          fontName: 'webfont',
          cssTemplateFontPath: helpers.root('src/assets/fonts/'),
          dest: {
              fontsDir: helpers.root('src/assets/fonts/'),
              stylesDir: helpers.root('src/assets/css/')
          }
      })
```

**Comment by evilebottnawi** [comment]
@wasa4587 `centerHorizontally: true`?

**Comment by wasa4587** [comment]
@evilebottnawi thanks for answer, i added `centerHorizontally: true` , and i've got the same result 
 
![image](https://user-images.githubusercontent.com/2035706/32962267-6fa3cb76-cb91-11e7-82b5-bb252c5b6ddc.png)

**Comment by evilebottnawi** [comment]
@wasa4587 add `vertical-align: center`

**Comment by wasa4587** [comment]
@evilebottnawi thanks for your answer again, I discovered it is a screen issue
I'm using a gaming laptop 4k small screen.

I used an external monitor and it's working fine there. 
![image](https://user-images.githubusercontent.com/2035706/32965084-1b918b40-cb9b-11e7-8755-1f100117c945.png)
